# Generated by Django 4.2.4 on 2023-10-10 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_committeeperweekday_alter_product_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='sold_products',
        ),
        migrations.CreateModel(
            name='SoldProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='product')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sell', verbose_name='sell')),
            ],
        ),
    ]
