# Generated by Django 4.2.4 on 2023-10-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_committeeperweekday_day_alter_sell_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoldProducts',
            new_name='SoldProduct',
        ),
        migrations.AlterField(
            model_name='committeeperweekday',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=200),
        ),
    ]
